/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CustomOrderRouteImport } from './routes/custom-order'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopProductIdRouteImport } from './routes/shop/$productId'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardUserIndexRouteImport } from './routes/dashboard/user/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardUserReviewsRouteImport } from './routes/dashboard/user/reviews'
import { Route as DashboardUserProfileRouteImport } from './routes/dashboard/user/profile'
import { Route as DashboardUserPaymentsRouteImport } from './routes/dashboard/user/payments'
import { Route as DashboardUserMyOrdersRouteImport } from './routes/dashboard/user/my-orders'
import { Route as DashboardAdminManageUsersRouteImport } from './routes/dashboard/admin/manage-users'
import { Route as DashboardAdminManageProductsRouteImport } from './routes/dashboard/admin/manage-products'
import { Route as DashboardAdminAddProductRouteImport } from './routes/dashboard/admin/add-product'
import { Route as DashboardAdminManageOrdersRouteImport } from './routes/dashboard/admin/Manage-Orders'
import { Route as DashboardAdminOrderIdRouteImport } from './routes/dashboard/admin/$orderId'
import { Route as DashboardAdminUpdateProductProductIdRouteImport } from './routes/dashboard/admin/update-product/$productId'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomOrderRoute = CustomOrderRouteImport.update({
  id: '/custom-order',
  path: '/custom-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ShopRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUserIndexRoute = DashboardUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardUserReviewsRoute = DashboardUserReviewsRouteImport.update({
  id: '/user/reviews',
  path: '/user/reviews',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUserProfileRoute = DashboardUserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUserPaymentsRoute = DashboardUserPaymentsRouteImport.update({
  id: '/user/payments',
  path: '/user/payments',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUserMyOrdersRoute = DashboardUserMyOrdersRouteImport.update({
  id: '/user/my-orders',
  path: '/user/my-orders',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminManageUsersRoute =
  DashboardAdminManageUsersRouteImport.update({
    id: '/manage-users',
    path: '/manage-users',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminManageProductsRoute =
  DashboardAdminManageProductsRouteImport.update({
    id: '/manage-products',
    path: '/manage-products',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminAddProductRoute =
  DashboardAdminAddProductRouteImport.update({
    id: '/add-product',
    path: '/add-product',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminManageOrdersRoute =
  DashboardAdminManageOrdersRouteImport.update({
    id: '/Manage-Orders',
    path: '/Manage-Orders',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminOrderIdRoute = DashboardAdminOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminUpdateProductProductIdRoute =
  DashboardAdminUpdateProductProductIdRouteImport.update({
    id: '/update-product/$productId',
    path: '/update-product/$productId',
    getParentRoute: () => DashboardAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom-order': typeof CustomOrderRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reviews': typeof ReviewsRoute
  '/shop': typeof ShopRouteWithChildren
  '/success': typeof SuccessRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop/': typeof ShopIndexRoute
  '/dashboard/admin/$orderId': typeof DashboardAdminOrderIdRoute
  '/dashboard/admin/Manage-Orders': typeof DashboardAdminManageOrdersRoute
  '/dashboard/admin/add-product': typeof DashboardAdminAddProductRoute
  '/dashboard/admin/manage-products': typeof DashboardAdminManageProductsRoute
  '/dashboard/admin/manage-users': typeof DashboardAdminManageUsersRoute
  '/dashboard/user/my-orders': typeof DashboardUserMyOrdersRoute
  '/dashboard/user/payments': typeof DashboardUserPaymentsRoute
  '/dashboard/user/profile': typeof DashboardUserProfileRoute
  '/dashboard/user/reviews': typeof DashboardUserReviewsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/user/': typeof DashboardUserIndexRoute
  '/dashboard/admin/update-product/$productId': typeof DashboardAdminUpdateProductProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom-order': typeof CustomOrderRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reviews': typeof ReviewsRoute
  '/success': typeof SuccessRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop': typeof ShopIndexRoute
  '/dashboard/admin/$orderId': typeof DashboardAdminOrderIdRoute
  '/dashboard/admin/Manage-Orders': typeof DashboardAdminManageOrdersRoute
  '/dashboard/admin/add-product': typeof DashboardAdminAddProductRoute
  '/dashboard/admin/manage-products': typeof DashboardAdminManageProductsRoute
  '/dashboard/admin/manage-users': typeof DashboardAdminManageUsersRoute
  '/dashboard/user/my-orders': typeof DashboardUserMyOrdersRoute
  '/dashboard/user/payments': typeof DashboardUserPaymentsRoute
  '/dashboard/user/profile': typeof DashboardUserProfileRoute
  '/dashboard/user/reviews': typeof DashboardUserReviewsRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/user': typeof DashboardUserIndexRoute
  '/dashboard/admin/update-product/$productId': typeof DashboardAdminUpdateProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom-order': typeof CustomOrderRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reviews': typeof ReviewsRoute
  '/shop': typeof ShopRouteWithChildren
  '/success': typeof SuccessRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop/': typeof ShopIndexRoute
  '/dashboard/admin/$orderId': typeof DashboardAdminOrderIdRoute
  '/dashboard/admin/Manage-Orders': typeof DashboardAdminManageOrdersRoute
  '/dashboard/admin/add-product': typeof DashboardAdminAddProductRoute
  '/dashboard/admin/manage-products': typeof DashboardAdminManageProductsRoute
  '/dashboard/admin/manage-users': typeof DashboardAdminManageUsersRoute
  '/dashboard/user/my-orders': typeof DashboardUserMyOrdersRoute
  '/dashboard/user/payments': typeof DashboardUserPaymentsRoute
  '/dashboard/user/profile': typeof DashboardUserProfileRoute
  '/dashboard/user/reviews': typeof DashboardUserReviewsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/user/': typeof DashboardUserIndexRoute
  '/dashboard/admin/update-product/$productId': typeof DashboardAdminUpdateProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/custom-order'
    | '/forgot-password'
    | '/gallery'
    | '/login'
    | '/register'
    | '/reviews'
    | '/shop'
    | '/success'
    | '/dashboard/admin'
    | '/shop/$productId'
    | '/shop/'
    | '/dashboard/admin/$orderId'
    | '/dashboard/admin/Manage-Orders'
    | '/dashboard/admin/add-product'
    | '/dashboard/admin/manage-products'
    | '/dashboard/admin/manage-users'
    | '/dashboard/user/my-orders'
    | '/dashboard/user/payments'
    | '/dashboard/user/profile'
    | '/dashboard/user/reviews'
    | '/dashboard/admin/'
    | '/dashboard/user/'
    | '/dashboard/admin/update-product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/about'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/custom-order'
    | '/forgot-password'
    | '/gallery'
    | '/login'
    | '/register'
    | '/reviews'
    | '/success'
    | '/shop/$productId'
    | '/shop'
    | '/dashboard/admin/$orderId'
    | '/dashboard/admin/Manage-Orders'
    | '/dashboard/admin/add-product'
    | '/dashboard/admin/manage-products'
    | '/dashboard/admin/manage-users'
    | '/dashboard/user/my-orders'
    | '/dashboard/user/payments'
    | '/dashboard/user/profile'
    | '/dashboard/user/reviews'
    | '/dashboard/admin'
    | '/dashboard/user'
    | '/dashboard/admin/update-product/$productId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/about'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/custom-order'
    | '/forgot-password'
    | '/gallery'
    | '/login'
    | '/register'
    | '/reviews'
    | '/shop'
    | '/success'
    | '/dashboard/admin'
    | '/shop/$productId'
    | '/shop/'
    | '/dashboard/admin/$orderId'
    | '/dashboard/admin/Manage-Orders'
    | '/dashboard/admin/add-product'
    | '/dashboard/admin/manage-products'
    | '/dashboard/admin/manage-users'
    | '/dashboard/user/my-orders'
    | '/dashboard/user/payments'
    | '/dashboard/user/profile'
    | '/dashboard/user/reviews'
    | '/dashboard/admin/'
    | '/dashboard/user/'
    | '/dashboard/admin/update-product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CustomOrderRoute: typeof CustomOrderRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ReviewsRoute: typeof ReviewsRoute
  ShopRoute: typeof ShopRouteWithChildren
  SuccessRoute: typeof SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-order': {
      id: '/custom-order'
      path: '/custom-order'
      fullPath: '/custom-order'
      preLoaderRoute: typeof CustomOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/user/': {
      id: '/dashboard/user/'
      path: '/user'
      fullPath: '/dashboard/user/'
      preLoaderRoute: typeof DashboardUserIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/user/reviews': {
      id: '/dashboard/user/reviews'
      path: '/user/reviews'
      fullPath: '/dashboard/user/reviews'
      preLoaderRoute: typeof DashboardUserReviewsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/user/profile': {
      id: '/dashboard/user/profile'
      path: '/user/profile'
      fullPath: '/dashboard/user/profile'
      preLoaderRoute: typeof DashboardUserProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/user/payments': {
      id: '/dashboard/user/payments'
      path: '/user/payments'
      fullPath: '/dashboard/user/payments'
      preLoaderRoute: typeof DashboardUserPaymentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/user/my-orders': {
      id: '/dashboard/user/my-orders'
      path: '/user/my-orders'
      fullPath: '/dashboard/user/my-orders'
      preLoaderRoute: typeof DashboardUserMyOrdersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/manage-users': {
      id: '/dashboard/admin/manage-users'
      path: '/manage-users'
      fullPath: '/dashboard/admin/manage-users'
      preLoaderRoute: typeof DashboardAdminManageUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/manage-products': {
      id: '/dashboard/admin/manage-products'
      path: '/manage-products'
      fullPath: '/dashboard/admin/manage-products'
      preLoaderRoute: typeof DashboardAdminManageProductsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/add-product': {
      id: '/dashboard/admin/add-product'
      path: '/add-product'
      fullPath: '/dashboard/admin/add-product'
      preLoaderRoute: typeof DashboardAdminAddProductRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/Manage-Orders': {
      id: '/dashboard/admin/Manage-Orders'
      path: '/Manage-Orders'
      fullPath: '/dashboard/admin/Manage-Orders'
      preLoaderRoute: typeof DashboardAdminManageOrdersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/$orderId': {
      id: '/dashboard/admin/$orderId'
      path: '/$orderId'
      fullPath: '/dashboard/admin/$orderId'
      preLoaderRoute: typeof DashboardAdminOrderIdRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/update-product/$productId': {
      id: '/dashboard/admin/update-product/$productId'
      path: '/update-product/$productId'
      fullPath: '/dashboard/admin/update-product/$productId'
      preLoaderRoute: typeof DashboardAdminUpdateProductProductIdRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminOrderIdRoute: typeof DashboardAdminOrderIdRoute
  DashboardAdminManageOrdersRoute: typeof DashboardAdminManageOrdersRoute
  DashboardAdminAddProductRoute: typeof DashboardAdminAddProductRoute
  DashboardAdminManageProductsRoute: typeof DashboardAdminManageProductsRoute
  DashboardAdminManageUsersRoute: typeof DashboardAdminManageUsersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardAdminUpdateProductProductIdRoute: typeof DashboardAdminUpdateProductProductIdRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminOrderIdRoute: DashboardAdminOrderIdRoute,
  DashboardAdminManageOrdersRoute: DashboardAdminManageOrdersRoute,
  DashboardAdminAddProductRoute: DashboardAdminAddProductRoute,
  DashboardAdminManageProductsRoute: DashboardAdminManageProductsRoute,
  DashboardAdminManageUsersRoute: DashboardAdminManageUsersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardAdminUpdateProductProductIdRoute:
    DashboardAdminUpdateProductProductIdRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardUserMyOrdersRoute: typeof DashboardUserMyOrdersRoute
  DashboardUserPaymentsRoute: typeof DashboardUserPaymentsRoute
  DashboardUserProfileRoute: typeof DashboardUserProfileRoute
  DashboardUserReviewsRoute: typeof DashboardUserReviewsRoute
  DashboardUserIndexRoute: typeof DashboardUserIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardUserMyOrdersRoute: DashboardUserMyOrdersRoute,
  DashboardUserPaymentsRoute: DashboardUserPaymentsRoute,
  DashboardUserProfileRoute: DashboardUserProfileRoute,
  DashboardUserReviewsRoute: DashboardUserReviewsRoute,
  DashboardUserIndexRoute: DashboardUserIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface ShopRouteChildren {
  ShopProductIdRoute: typeof ShopProductIdRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopProductIdRoute: ShopProductIdRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CustomOrderRoute: CustomOrderRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ReviewsRoute: ReviewsRoute,
  ShopRoute: ShopRouteWithChildren,
  SuccessRoute: SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
